name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: mysite.settings
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # Should be the same as in runtime.txt (python-3.11) / ugyanannak kell lennie,mint a runtime.txt-ben (python-3.11)

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#new steps begin új lépések kezdete
      - name: Linting check (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Security check (bandit)
        run: |
          bandit -r .

      - name: Run Unit Tests (pytest)
        run: |
          pytest --ds=mysite.settings
#new steps end új lépések vége

      - name: Quick check
        run: python -c "import django,sys; print('Django', django.get_version(), '| Python', sys.version.split()[0])"
